### ISSUE TITLE
Is the dataset weighted in favor of "NotTheOnion"?

### ISSUE THREAD

**Issue by JordanReiter** [patlaff/redditOnions#2]
It seems like most articles are from NotTheOnion rather than TheOnion, possibly because there's just more volume and activity in that subreddit. Instead of pulling 100 from a combined request, I'd suggest doing to separate requests, pulling in 50 from each, and combining them together.

**Comment by patlaff** [comment]
I noticed that too. I'd also just like to get more than 100 posts in the bank, which seems to be the reddit open api limit, so breaking them out into two separate requests, would give me 100 of each.  If I use 2 different requests, can I use the same headlineLookup array you set up for each? Or will I need a different lookup array for each request?

**Comment by JordanReiter** [comment]
You can use the same array. It's pretty straightforward. Basically I would create a "fillHeadlines" function rather than duplicating code. Then write to the global variables.
